name: docker-build:slam-toolbox

on:
  push:
    branches: 
      - master
      - develop

jobs:
  build-n-push-slam-toolbox:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: docker/slam-toolbox/
          file: docker/slam-toolbox/Dockerfile
          platforms: linux/amd64
          push: true
          tags: cogniteam/slam-toolbox